### ISSUE TITLE
Make Assholes Glorious Again

### ISSUE THREAD

**Issue by Lagg** [devunt/make-gis-great-again#1]
Makes Stupid Cunts Think They're Clever Again

Nice implementation though. Appropriate that an american company gets taken down by a stock image host, and the workaround is named after a stock company that took america down.

**Comment by sudofox** [comment]
Hello,

GitHub Issues is not a comments section; this issue is invalid.

**Comment by Lagg** [comment]
Quite. Yet the project author is someone who gets off on making light of a brand that gets off on attacking weak segments of society - like some kind of pathetic cocksucker. And I get off on making sure they know what they are. I am also on topic for the project's  scope. We clear? k. 😄 

(apologies to you and yours for language though)

**Comment by indecisivemal** [comment]
I do agree the name is not clever or funny. It comes off as a hat-tip to someone who deserves no respect.
