### ISSUE TITLE
Chrome has both....

### ISSUE THREAD

**Issue by SundaySnooker** [devunt/make-gis-great-again#10]
Guys
Chrome has extension that has BOTH "View Image" and "Search by Image"...
https://chrome.google.com/webstore/detail/view-image/jpcmhcelnjdmblfmjabdeclccemkghjk

Aaannnd so is FireFox now...
https://addons.mozilla.org/en-US/firefox/addon/view-image/

**Comment by devunt** [comment]
It is good to have many alternatives of the software since there's a possibility to development to be stopped by any reason. Anyway, mine was first!
