### ISSUE TITLE
Broken again

### ISSUE THREAD

**Issue by koberulz** [devunt/make-gis-great-again#100]
Seems to be broken on Google Image search again, as of the past week or so, Tampermonkey script version 1.5.0.18. The update link actually links to an even older version, 1.5.0.8.

**Comment by Procyon-b** [comment]
I've updated the script.
Force-update it.

**Comment by koberulz** [comment]
I'm now on 1.5.0.19, but still no resolution.

**Comment by Procyon-b** [comment]
Can you take a screenshot so I can see what it looks like ?
Anyway, I'll continue testing until I encounter the same problem.

**Comment by koberulz** [comment]
Hmm. Seems to be working now.
