### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by artdog123** [devunt/make-gis-great-again#28]
Seems like Google have changed something as the extension isn't working for me anymore.

**Comment by devunt** [comment]
Could you provide more detailed information on it?
What is your browser and what is your extension version?

**Comment by artdog123** [comment]
Yes sorry.
Version 64.0.3282.167 (Official Build) (64-bit)
Mac Os 10.13.3 
Google Search "View Image" Button 1.3

It was working for a few days.

**Comment by devunt** [comment]
Hmm. I'm using the same version as yours but it works for me.
What is your console log saying? You can check in by pressing F12 on chrome, and select the "console" tab, and refreshing the search page, and then click any images on the list.

**Comment by Sollembum78** [comment]
Just to add to conversation, using latest chrome on windows 10 64bit and it works perfectly fine, I see no changes from google. Just updated chrome now, to check, and it's fine.

**Comment by artdog** [comment]
Hmm. Now its working. Must have been a strange glitch either in the browser or in my brain.
