### ISSUE TITLE
Just some feedback

### ISSUE THREAD

**Issue by alemanetz** [devunt/make-gis-great-again#4]
Hey, I noticed the button doesn't show up when going into sites like [this one](https://www.google.com/imgres?imgurl=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2Fthumb%2F3%2F3a%2FCat03.jpg%2F1200px-Cat03.jpg&imgrefurl=https%3A%2F%2Fen.wiktionary.org%2Fwiki%2Fcat&docid=3aBlXpmFZqFG2M&tbnid=hMjxy8pUhhc4QM%3A&vet=1&w=1200&h=1199&bih=616&biw=1332&ved=0ahUKEwjVxc7tgavZAhVPuFMKHbrvAQMQMwhBKAEwAQ&iact=c&ictx=1). Also, when changing from one preview to another (i.e. when choosing a related image) and clicking the button it just shows the original image you clicked, not the related image. Thanks for the extension by the way!

**Comment by devunt** [comment]
Fixed by #22 which is @AHOHNMYC submitted.
