### ISSUE TITLE
Tampermonkey problem

### ISSUE THREAD

**Issue by PentagramTr** [devunt/make-gis-great-again#50]
Hi.

Script does not working with Tampermonkey.

![scr](https://user-images.githubusercontent.com/34379403/36610270-c5c69c44-18e0-11e8-8a76-a51e083f2a5d.png)

**Comment by Almo7aya** [comment]
Hello @PentagramTr,
Did you implement the userscript `gis-vib.user.js` correctly in Tampermonkey.
You should add where the script will run from the settings panel.

**Comment by PentagramTr** [comment]
Hi.

I added the code below to Tampermonkey.But it still not working.
https://paste.ubuntu.com/p/vsmBpjwkWr
https://i.hizliresim.com/p6bd1r.png

Would you give a screenshot about the "Settings panel" you mentioned?What should I add?I doesn't have software knowledge.

@Almo7aya

**Comment by Almo7aya** [comment]
Hello @PentagramTr,
get the lastest userscript `gis-vib.user.js` from here https://raw.githubusercontent.com/devunt/make-gis-great-again/master/gis-vib.user.js

and add it to the the scripts list inside the Tamermonkey dashboard.
Here
![Tamermonkey dashboard](https://user-images.githubusercontent.com/17254073/36641443-88002590-1a40-11e8-8145-25dc1837e012.PNG)


and paste the userscript in the text editor.
![settingstab](https://user-images.githubusercontent.com/17254073/36641447-93d9e8b0-1a40-11e8-9421-7382c19ae166.PNG)


after adding the userscript click the settings panel and check the Includes/Excludes List for `http*://*.google.tld/search*tbm=isch*`
![url](https://user-images.githubusercontent.com/17254073/36641449-9d21a084-1a40-11e8-9a48-bb08e33af356.PNG)


By doing these steps the script should run.

**Comment by PentagramTr** [comment]
I tried all but it's still not working.You can now close this issue.Because I'm now using the Chrome extension.
Thank you.

https://i.hizliresim.com/5DNY1j.png
https://i.hizliresim.com/0E0yo9.png
https://i.hizliresim.com/4ap0v4.png
https://i.hizliresim.com/OorEpQ.png

https://i.hizliresim.com/W7Xbm8.png

**Comment by BrkIt** [comment]
Change
`// @include         http*://*.google.tld/search*tbm=isch*`

To whatever the tld is for your country.

Example:
`// @include         http*://*.google.com/search*tbm=isch*
// @include         http*://*.google.com.au/search*tbm=isch*`

**Comment by AHOHNMYC** [comment]
@BrkIt There is more clean way. Adding `// @include http*://*.google.com.tld/search*tbm=isch*`
Anyway its Tampermonkey's trouble.

**Comment by PentagramTr** [comment]
OK now it works. You can now close this issue.
Thank you


![1adsiz](https://user-images.githubusercontent.com/34379403/36915835-2538e0ba-1e63-11e8-81b9-1ea2b91e471a.png)
![adsiz](https://user-images.githubusercontent.com/34379403/36915836-255e244c-1e63-11e8-990f-92f246389834.png)
