### ISSUE TITLE
Tr Description

### ISSUE THREAD

**Issue by PentagramTr** [devunt/make-gis-great-again#58]
> description     This userscript adds "View Image" button to Google Image Search results.

> description:tr Bu komut dosyası, Google Görseller arama sonuçlarına "Resmi Görüntüle" düğmesini ekler.

Please add this description.

Another problem 
Would you please write G with capital letter?

`tr: 'Resmi görüntüle',` --- `tr: 'Resmi Görüntüle',`

**Comment by Almo7aya** [comment]
Ok, I'll add them.
