### ISSUE TITLE
Stopped working as of 14/03/2018

### ISSUE THREAD

**Issue by ukch** [devunt/make-gis-great-again#64]
Using the Firefox extension, the 'view image' button no longer displays as of today. Until yesterday it was working fine.

**Comment by Qsaws** [comment]
Same thing on Chrome, with the extension or the script.

**Comment by Perkin5** [comment]
Me too on Firefox - as of couple of days ago. Is there a fix coming?

**Comment by thinkpad4** [comment]
Google changed something

**Comment by Akshat-h** [comment]
Other similar extensions are still working. But i don't like them. Hope you fix it soon.

**Comment by C0dekid** [comment]
It stopped working for aswell

**Comment by Nathan2055** [comment]
Looks like someone's already found the problem and opened PR #66 to fix it. That just needs to be pulled in. @devunt

**Comment by devunt** [comment]
Fixed by #66.
