### ISSUE TITLE
Google is fighting against your extension

### ISSUE THREAD

**Issue by SoufianAkh** [devunt/make-gis-great-again#65]
- Are you using browser extension or userscript?
Browser Extension
- Is "Make GIS great again" working on other pages? 
No

- Is error disappeared when you changed extension/userscript to userscript/extension?
No

- Link to page where error occurs
All images

- Screenshot of page where error occurs
All images

- Screenshot of Developer tools' "Console" (Firefox — `Control+Shift+K`, Chrome — `Ctrl+Shift+J`)
https://i.imgur.com/4vPYD3h.png

**Comment by Nathan2055** [comment]
Already reported in issue #64 and fixed with PR #66. Waiting on a pull from the developer.

**Comment by devunt** [comment]
Fixed by #66.
