### ISSUE TITLE
Firefox Extension - Broken

### ISSUE THREAD

**Issue by WASasquatch** [devunt/make-gis-great-again#69]
I'm assuming just a GCode change, but thought I'd let you know before the review rating gets tarnished on Mozilla Add-Ons.

- Are you using browser extension or userscript?
Extension
- Is "Make GIS great again" working on other pages? 
No
- Is error disappeared when you changed extension/userscript to userscript/extension?
No
- Link to page where error occurs
images.google.com
- Screenshot of page where error occurs
https://prnt.sc/isqk29
- Screenshot of Developer tools' "Console" (Firefox — `Control+Shift+K`, Chrome — `Ctrl+Shift+J`)
https://prnt.sc/isqk6s

**Comment by devunt** [comment]
Fixed!
