### ISSUE TITLE
 gis-vib.user.js:57 Uncaught TypeError: Cannot read property 'closest' of null

### ISSUE THREAD

**Issue by carbolymer** [devunt/make-gis-great-again#75]
- Are you using browser extension or userscript?
extension
- Is "Make GIS great again" working on other pages? 
dunno
- Is error disappeared when you changed extension/userscript to userscript/extension?
haven't tried
- Link to page where error occurs
https://www.google.com/search?q=seteais+palace&num=100&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjf3prU993aAhVEuxQKHUgZDMsQ_AUICigB&biw=2844&bih=1526#imgrc=Rfj-87Pu1QPc5M:
- Screenshot of page where error occurs
n/a
- Screenshot of Developer tools' "Console" (Firefox — `Control+Shift+K`, Chrome — `Ctrl+Shift+J`)
![error](https://user-images.githubusercontent.com/228866/39401133-8582ccbc-4b3e-11e8-8da2-6ced7e121631.png)

The button does not appear. Exact error from Developer Tools is attached.

**Comment by Fire-Dragon-DoL** [comment]
I can confirm, same problem

**Comment by wachunei** [comment]
Same here, thumbnail selector must have changed.

**Comment by ltdicai** [comment]
Changing the thumbnail selector from 
`let thumbnail = document.querySelector('img[name="' + container.dataset.itemId + '"]');` 
to 
`let thumbnail = document.querySelector('img[id="' + container.dataset.itemId + '"]');`
works just fine (tested on the userscript).

**Comment by apcamargo** [comment]
Same problem
