### ISSUE TITLE
Neither userscript or extension work anymore

### ISSUE THREAD

**Issue by GuyInDogSuit** [devunt/make-gis-great-again#78]
- Are you using browser extension or userscript?
- Is "Make GIS great again" working on other pages? 
- Is error disappeared when you changed extension/userscript to userscript/extension?
- Link to page where error occurs
- Screenshot of page where error occurs
- Screenshot of Developer tools' "Console" (Firefox — `Control+Shift+K`, Chrome — `Ctrl+Shift+J`)

-I tried both the extension and the script.
-It does not work on ANY Google Image Search result.
-Error persists regardless of which version I use.
-Link to example page:
https://www.google.com/search?sa=G&hl=en&q=gorillaz+gorillaz+album+cover&tbm=isch&tbs=simg:CAQSlwEJaBjozYfv8WkaiwELEKjU2AQaBAgVCAQMCxCwjKcIGmIKYAgDEijAEvoDnAKwAvwDyAatCp4CuxLHBtcmiTOqIdIm6TyBM4AzijPqPK4mGjA5uLIX5mrpnkqI5SjuAzhRKLr-8aex8d057_1Qf_1RObcqH4zvoezDfQg_1BeyOs9PmUgBAwLEI6u_1ggaCgoICAESBHCwrW8M&ved=0ahUKEwjj1Nrd0ejaAhUH0lMKHR-ICtUQ2A4IJygB&biw=1920&bih=900#imgrc=arvpscqacf05bM:
-Screenshots attached.
![screenshot 1](https://user-images.githubusercontent.com/13460691/39559410-d7ec9406-4e4a-11e8-9dac-ea9e36e8c515.png)
![screenshot 2](https://user-images.githubusercontent.com/13460691/39559412-dbc92382-4e4a-11e8-8491-7e0bf9755d83.png)

**Comment by AncalagonTheBlack** [comment]
I can confirm that. Same problem affects me.

**Comment by the3ye** [comment]
Same here. Script on Safari

**Comment by raszpl** [comment]
I fixed it ;-), replace this function:
```
function addButton(node) {
  if (node.nodeType === Node.ELEMENT_NODE) {
    if (node.classList.contains('irc_ris')) {
      let container = node.closest('.irc_c');

      let similarImages = node.querySelectorAll('.rg_l');
      [].forEach.call(similarImages, (image) => {
        image.addEventListener('click', updateLinkAfterClickOnSimilar);
      });

//      let thumbnail = document.querySelector('img[id="' + container.dataset.itemId + '"]');
//      let meta = thumbnail.closest('.rg_bx').querySelector('.rg_meta');

      var container = node.querySelector('.irc_rimask.irc_rist');
      let meta = container.querySelector('.notranslate');

      let metadata = JSON.parse(meta.innerHTML);
      let src = metadata.ou;

      var container = node.closest('.irc_c');

      let buttons = container.querySelector('.irc_but_r tr');

      let button = buttons.querySelector('td.mgisga');
      if (button === null) {
        let openButton = buttons.querySelector('td');

        button = openButton.cloneNode(true);
        button.classList.add('mgisga');
        button.querySelector('a span:nth-child(2)').innerText = localizedViewImage;

        let link = button.querySelector('a');
        link.href = src;
        link.className = '';
        link.removeAttribute('data-cthref');
        link.removeAttribute('jsaction');

        openButton.after(button);
      }

      let link = button.querySelector('a');
      link.href = src;
    }
  }
}
```

Cant be bothered with official way of sending patches (forking repo etc)

**Comment by GuyInDogSuit** [comment]
How do I do that?

**Comment by SoufianAkh** [comment]
@GuyInDogSuit The developer of the extension has to add this.

**Comment by raszpl** [comment]
install https://addons.mozilla.org/en-US/firefox/addon/tampermonkey/, use raw script in tempermonkey instead of separate extension. Thats how I use it.

**Comment by p1r473** [comment]
Use this one instead
https://chrome.google.com/webstore/detail/view-image/jpcmhcelnjdmblfmjabdeclccemkghjk/related?hl=en

**Comment by GuyInDogSuit** [comment]
That one works! Thanks!



_______________________________

*"We are all searching for someone whose demons play well with ours."*

**Comment by raszpl** [comment]
not according to the reviews :)

**Comment by pahakalle** [comment]
Userscript works fine for me on chrome 66.0.3359.139

**Comment by jhult** [comment]
The Chrome extension does not currently work (see all the comments on the store page).

However, pulling in the latest [gis-vib.user.js](https://github.com/devunt/make-gis-great-again/blob/master/gis-vib.user.js) updates (from 4 days ago) made the extension work (using [this how-to](https://stackoverflow.com/a/16688027/)).
.
@dev-id, you need to update the Chrome extension.

**Comment by raszpl** [comment]
Thank you Dave/@dev-id for doing the leg work and submitting my patch.
@jhult dev-id is not the owner of this repo, he cant update chrome extension. devunt is the owner. I suspect he is either waiting to see if it doesnt change again, or submitted change and it wasnt updated yet in google store - Im talking out of my ass here, I have no experience with Google store/extension bureaucracy ;) Either way my patch is still working fine.

**Comment by onmyouji** [comment]
@raszpl What browser do you use? Seems like it's not working on the latest Chrome (Version 66.0.3359.181)

**Comment by jhult** [comment]
@onmyouji, the Chrome extension does not currently work. I am using Chrome Version 66.0.3359.170.

There are only 2 options:
1. Wait until @devunt updates the Chrome extension
2. Create a local unpacked version of the extension and manually update gis-vib.user.js

**Comment by carbolymer** [comment]
The current master as of 21.05.2018 works as unpacked extension.

**Comment by devunt** [comment]
Fixed version of the extension is released on both Chrome Web Store and Firefox Add-ons. Sorry for the delay!

**Comment by raszpl** [comment]
thank you devunt for absolutely life saving extension!
